### ISSUE TITLE
A way to pass firmware in http request

### ISSUE THREAD

**Issue by nvecchio1** [G6EJD/ESP32-OTA-Example#2]
Hi,
i'm tring to update my esp32 with ota update.
There's a way to pass my firmware directly in http request?
ty, let me know.

**Comment by G6EJD** [comment]
https://lastminuteengineers.com/esp32-ota-web-updater-arduino-ide/

**Comment by nvecchio1** [comment]
In this link, show how to import file with form.
I need a way to write something in the http request (url).
I ask ask if it is possible and u know how to pass, for example the directory of .bin file" in the request url.
